const actionTypes = {
    "NEW_MOVE" : "NEW_MOVE",
    "GENERATE_CANDIDATE_MOVES":"GENERATE_CANDIDATE_MOVES",
    "CLEAR_CANDIDATE_MOVES":"CLEAR_CANDIDATE_MOVES",
    "UPDATE_BOARD":"UPDATE_BOARD",
}

export default actionTypes